name: ServerCore
version: '${project.version}'
main: com.jbuelow.servercore.ServerCore
api-version: '1.20'

depend:
  - Vault

commands:
  trust:
    description: Trusts a player with building privileges
    usage: /<command> <player>
    permission: servercore.command.trust
  untrust:
    description: Revokes building privileges from a player
    usage: /<command> <player>
    permission: servercore.command.untrust