name: Maven CI

on:
  push:
  pull_request:

jobs:
  compile_test_package:
    name: Compile, Test and Package
    runs-on: ubuntu-24.04

    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 21
        uses: actions/setup-java@v1
        with:
          java-version: 21

      - name: Compile project
        run: mvn -B compile --file pom.xml

      - name: Test project
        run: mvn -B test --file pom.xml

      - name: Package project
        run: mvn -B package --file pom.xml
